<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SubCategoryDetail;

class SubCategoryDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $SubCategoryDetail = [
            "AD User Account Creation",
            "AD User Account Modification",
            "AD User Account Deletion",
            "AD Password Reset",
            "AD Account Unlock",
            "AD Security Group Creation",
            "AD Security Group Modification",
            "AD Security Group Deletion",
            "Shared Folder Creation",
            "Shared Folder Modification",
            "Shared Folder Deletion",
            "Shared Folder Access",
            "Shared Folder Mapping",
            "Data Backup",
            "Data Restoration And Datra Transfer",
            "Email Account Password Reset",
            "Email Account Creation",
            "Email Account Modification",
            "Email Account Deletion",
            "Distribution List Creation",
            "Distribution List Modification",
            "Distribution List Deletion",
            "Shared Mailbox Creation",
            "Shared Mailbox Deletion",
            "Shared Mailbox Modification",
            "Email Archiving",
            "Email Account Creation",
            "Email Account Modification",
            "Email Account Deletion",
            "Installation And Configuration",
            "Support and Troubleshooting",
            "Installation And Configuration",
            "Support, Troubleshooting And Patch or Version Update",
            "Support",
            "Setup & Configuration",
            "Procurement",
            "Support",
            "Setup & Configuration",
            "Procurement",
            "Support",
            "Setup & Configuration",
            "Procurement",
            "Support",
            "Procurement",
            "Support",
            "Setup & Configuration",
            "Procurement",
            "Account Creation",
            "License Request",
            "Support and Troubleshooting",
            "Account Creation",
            "License Request",
            "Support and Troubleshooting",
            "Account Creation",
            "License Request",
            "Support and Troubleshooting",
            "Account Creation",
            "License Request",
            "Support and Troubleshooting",
            "Account Creation",
            "Account Deletion",
            "Installation",
            "General Function Support",
            "Account Creation",
            "Account Deletion",
            "Installation",
            "General Function Support ",
            "Account Creation",
            "Account Deletion",
            "Security Policy",
            "Intrusion Prevention System",
            "Loading, support, maintance",
            "CCTV Tech Support",
            "Request for CCTV Footage",
            "SKYPE, ZOOM, MS TEAMS AND VIBER, FB MESSENGER Access Creation",
            "Account Creation",
            "Account Deletion",
            "Support and Troubleshooting",
            "Web Hosting And Services Renewal ",
            "Website (Revision/Modification)",
            "Account Creation",
            "Support, Troubleshooting And Update",
            "Web Hosting And Services Renewal ",
            "Website (Revision/Modification)",
            "Account Creation",
            "Support, Troubleshooting And Update",
            "Web Hosting And Services Renewal ",
            "Website (Revision/Modification)",
            "Account Creation",
            "Support, Troubleshooting And Update",
            "Account Creation",
            "Support, Troubleshooting And Update",
            "Revision/Modification",
            "Account Creation",
            "Support, Troubleshooting And Update",
            "Revision/Modification",
            "Account Creation",
            "Support, Troubleshooting And Update",
            "Revision/Modification",
            "Account Creation",
            "Support, Troubleshooting And Update",
            "Revision/Modification",
            "Account Creation",
            "Support, Troubleshooting And Update",
            "Revision/Modification",
            "Account Creation",
            "Support, Troubleshooting And Update",
            "Revision/Modification"
        ];

        $RequestType = [
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Incident",
            "Request",
            "Incident",
            "Incident",
            "Incident",
            "Request",
            "Incident",
            "Request",
            "Request",
            "Incident",
            "Incident",
            "Request",
            "Incident",
            "Request",
            "Incident",
            "Incident",
            "Request",
            "Request",
            "Request",
            "Incident",
            "Request",
            "Request",
            "Incident",
            "Request",
            "Request",
            "Incident",
            "Request",
            "Request",
            "Incident",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Request",
            "Incident",
            "Incident",
            "Request",
            "Incident",
            "Request",
            "Request",
            "Request",
            "Request",
            "Incident",
            "Request",
            "Request",
            "Request",
            "Incident",
            "Request",
            "Request",
            "Request",
            "Incident",
            "Request",
            "Request",
            "Request",
            "Incident",
            "Request",
            "Incident",
            "Request",
            "Request",
            "Incident",
            "Request",
            "Request",
            "Incident",
            "Request",
            "Request",
            "Incident",
            "Request",
            "Request",
            "Incident",
            "Request",
            "Request",
            "Incident",
            "Request",
        ];

        $SubCatID = [1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10, 10, 11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16, 17, 17, 17, 18, 18, 18, 18, 19, 19, 19, 20, 20, 21, 22, 22, 23, 24, 24, 24, 25, 25, 25, 25, 26, 26, 26, 26, 27, 27, 27, 27, 28, 28, 28, 29, 29, 29, 30, 30, 30, 31, 31, 31, 32, 32, 32, 33, 33, 33];
        
        $PriorityID = [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 5, 5, 5, 10, 4, 6, 10, 3, 3, 10, 4, 10, 3, 3, 10, 6, 6, 4, 11, 11, 11, 6, 6, 4, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 4, 7, 4, 11, 6, 6, 6, 4, 6, 9, 6, 4, 6, 9, 6, 4, 6, 9, 6, 4, 6, 4, 6, 6, 4, 9, 6, 4, 9, 6, 4, 9, 6, 4, 9, 6, 4, 9];

        for($x = 0; $x<count($SubCategoryDetail); $x++) {
            $s = new SubCategoryDetail;
            $s->SubCategoryDetails = $SubCategoryDetail[$x];
            $s->SubCategoryID = $SubCatID[$x];
            $s->PriorityID = $PriorityID[$x];
            $s->RequestType = $RequestType[$x];
            $s->save();
        }
    }
}
